suppress error log when postgre database does not exist
May 24, 2019 1:25:14 PM org.postgresql.Driver connect
SEVERE: Connection error:
org.postgresql.util.PSQLException: FATAL: database "hugegraph" does not exist

Change-Id: I48aebac67ec98f5c05b96239b497940150542dcc