fix tasks are sometimes submitted twice (#1130)
* fix tasks are sometimes submitted twice
  also fix server id NPE when truncate with temp graph
* fix rocksdb conflict: no setMaxSubcompactions()
  NoSuchMethodError: org.rocksdb.DBOptionsInterface.setMaxSubcompactions
* fix warnings

Change-Id: Ia9d509c57422eb27b11797aa3567a83101610080