fix rocksdb conflict: no setMaxSubcompactions()
Change-Id: If3884c0aa0a8a4cd1f9478d132b1f5ff27ade6fc
NoSuchMethodError: org.rocksdb.DBOptionsInterface.setMaxSubcompactions