fix(pd-store): fix hstore backend core tests failure (#2431)
After this commit, the core tests of hstore expect the following tests to fail:

```text
Failures:
  EdgeCoreTest.testScanEdgeInPaging:5214 expected:<18> but was:<0>
  MultiGraphsTest.testCopySchemaWithMultiGraphs:121
  VertexCoreTest.testAddOlapRangeAndOlapSecondaryProperties:2491 expected:<1> but was:<0>
  VertexCoreTest.testAddOlapRangeProperties:2344 expected:<1> but was:<0>
  VertexCoreTest.testAddOlapSecondaryProperties:2254 expected:<1> but was:<0>
  VertexCoreTest.testQueryOlapRangeAndRegularSecondaryProperties:2638 expected:<1> but was:<0>
  VertexCoreTest.testQueryOlapWithUpdates:2725 expected:<1> but was:<0>
  VertexCoreTest.testScanVertexInPaging:7606 expected:<10> but was:<1>
Errors:
  EdgeCoreTest.testQueryOutEdgesOfVertexBySortkeyWithMoreFields:3912 » HgStoreClient
  EdgeCoreTest.testQueryOutEdgesOfVertexBySortkeyWithMoreFieldsInPage:4131 » HgStoreClient
  EdgeCoreTest.testQueryOutEdgesOfVertexBySortkeyWithPrefix:3704 » HgStoreClient
  EdgeCoreTest.testQueryOutEdgesOfVertexBySortkeyWithPrefixInPage:3800 » HgStoreClient
  EdgeCoreTest.testQueryOutEdgesOfVertexBySortkeyWithRange:3607 » HgStoreClient ...
  MultiGraphsTest.testCreateGraphWithSameNameDifferentBackends:289->openGraphWithBackend:381 » Runtime
  RamTableTest.testReloadAndQuery:112 » Huge Failed to load ramtable
  RamTableTest.testReloadAndQueryWithBigVertex:369 » Huge Failed to load ramtabl...
  RamTableTest.testReloadAndQueryWithMultiEdges:239 » Huge Failed to load ramtab...
  RamTableTest.testReloadAndQueryWithProperty:444 » Huge Failed to load ramtable
  RamTableTest.testReloadFromFileAndQuery:159 » Huge Failed to load ramtable
  VertexCoreTest.testQueryByPropertyInPageWithLimitGtPageSize:8337 » IllegalArgument
  VertexCoreTest.testQueryByRangeIndexInPage:8568 » IllegalArgument Undefined in...
  VertexCoreTest.testQueryBySingleRangePropertyInPage:8423 » IllegalArgument Und...
```

---------

Co-authored-by: VGalaxies <vgalaxies@apache.org>